import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

interface AgentManifest {
  id: string;
  name: string;
  version: string;
  description?: string;
  permissions?: string[];
  trustLevel?: string;
  limits?: Record<string, number>;
  a2aSkills?: Array<{
    id: string;
    name: string;
    description?: string;
    inputSchema?: Record<string, unknown>;
  }>;
  [key: string]: unknown;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const agentsDir = resolve(__dirname, "../../../agents");
const outputPath = resolve(__dirname, "../src/lib/manifests.ts");

const manifests: AgentManifest[] = [];

if (existsSync(agentsDir)) {
  const entries = readdirSync(agentsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const manifestPath = join(agentsDir, entry.name, "manifest.json");
    if (!existsSync(manifestPath)) continue;
    try {
      const raw = readFileSync(manifestPath, "utf-8");
      const manifest = JSON.parse(raw) as AgentManifest;
      manifests.push(manifest);
    } catch {
      // skip invalid manifests
    }
  }
}

const output = `// Auto-generated by scripts/generate-manifests.ts — do not edit
export interface AgentManifest {
  id: string;
  name: string;
  version: string;
  description?: string;
  permissions?: string[];
  trustLevel?: string;
  limits?: Record<string, number>;
  a2aSkills?: Array<{
    id: string;
    name: string;
    description?: string;
    inputSchema?: Record<string, unknown>;
  }>;
  [key: string]: unknown;
}

export const AGENT_MANIFESTS: AgentManifest[] = ${JSON.stringify(manifests, null, 2)};
`;

writeFileSync(outputPath, output, "utf-8");
console.log(`Generated ${manifests.length} manifests → ${outputPath}`);
