// Auto-generated by scripts/generate-manifests.ts — do not edit
export interface AgentManifest {
  id: string;
  name: string;
  version: string;
  description?: string;
  permissions?: string[];
  trustLevel?: string;
  limits?: Record<string, number>;
  a2aSkills?: Array<{
    id: string;
    name: string;
    description?: string;
    inputSchema?: Record<string, unknown>;
  }>;
  [key: string]: unknown;
}

export const AGENT_MANIFESTS: AgentManifest[] = [
  {
    "id": "coder",
    "name": "Coder Agent",
    "version": "0.1.0",
    "description": "Reviews code, suggests tests, and proposes refactors.",
    "preferredModel": "gpt-4o-mini",
    "entryPoint": "agents/coder/dist/index.js",
    "requiredSkills": [],
    "permissions": [
      "memory.read",
      "memory.write",
      "llm.execute",
      "tools.execute",
      "filesystem.read",
      "shell.execute"
    ],
    "trustLevel": "semi-autonomous",
    "limits": {
      "maxTokensPerRequest": 4096,
      "requestsPerMinute": 60
    },
    "a2aSkills": [
      {
        "id": "code_review",
        "name": "Code Review",
        "description": "Review a diff or code snippet and return findings.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "code_review"
            },
            "diff": {
              "type": "string"
            },
            "context": {
              "type": "string"
            },
            "guidelines": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type",
            "diff"
          ]
        }
      },
      {
        "id": "test_suggest",
        "name": "Test Suggestions",
        "description": "Suggest tests for a given file or snippet.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "test_suggest"
            },
            "code": {
              "type": "string"
            },
            "filePath": {
              "type": "string"
            },
            "framework": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "code"
          ]
        }
      },
      {
        "id": "refactor_suggest",
        "name": "Refactor Suggestions",
        "description": "Recommend refactors for a code snippet.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "refactor_suggest"
            },
            "code": {
              "type": "string"
            },
            "goal": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "code"
          ]
        }
      },
      {
        "id": "run_command",
        "name": "Run Command",
        "description": "Execute a shell command (allowlisted) and return output.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "run_command"
            },
            "command": {
              "type": "string"
            },
            "args": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "cwd": {
              "type": "string"
            },
            "timeoutMs": {
              "type": "integer",
              "minimum": 100,
              "maximum": 60000
            },
            "allowNonZeroExit": {
              "type": "boolean"
            }
          },
          "required": [
            "type",
            "command"
          ]
        }
      },
      {
        "id": "repo_summary",
        "name": "Repository Summary",
        "description": "Summarize a repository using README and directory listing.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "repo_summary"
            },
            "root": {
              "type": "string"
            }
          },
          "required": [
            "type"
          ]
        }
      }
    ]
  },
  {
    "id": "monitor",
    "name": "Monitor Agent",
    "version": "0.1.0",
    "description": "Tracks URLs or feeds and emits alerts when content changes.",
    "preferredModel": "gpt-4o-mini",
    "entryPoint": "agents/monitor/dist/index.js",
    "requiredSkills": [],
    "permissions": [
      "memory.read",
      "memory.write",
      "tools.execute",
      "network.fetch"
    ],
    "trustLevel": "monitored-autonomous",
    "limits": {
      "requestsPerMinute": 30,
      "toolCallsPerMinute": 60
    },
    "tools": [
      {
        "id": "builtin:http_fetch",
        "enabled": true
      }
    ],
    "a2aSkills": [
      {
        "id": "monitor_add",
        "name": "Add Monitor",
        "description": "Add a URL to the monitoring list.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "monitor_add"
            },
            "url": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "notifyUrl": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "url"
          ]
        }
      },
      {
        "id": "monitor_remove",
        "name": "Remove Monitor",
        "description": "Remove a watcher by id.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "monitor_remove"
            },
            "id": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "id"
          ]
        }
      },
      {
        "id": "monitor_check",
        "name": "Check Monitors",
        "description": "Check all watchers (or a specific watcher).",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "monitor_check"
            },
            "id": {
              "type": "string"
            }
          },
          "required": [
            "type"
          ]
        }
      },
      {
        "id": "monitor_list",
        "name": "List Monitors",
        "description": "List current watchers.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "monitor_list"
            }
          },
          "required": [
            "type"
          ]
        }
      }
    ]
  },
  {
    "id": "researcher",
    "name": "Research Agent",
    "version": "0.1.0",
    "description": "Ingests sources, stores knowledge, and answers questions from memory.",
    "preferredModel": "gpt-4o-mini",
    "entryPoint": "agents/researcher/dist/index.js",
    "requiredSkills": [],
    "permissions": [
      "memory.read",
      "memory.write",
      "tools.execute",
      "network.fetch",
      "filesystem.read",
      "llm.execute"
    ],
    "trustLevel": "semi-autonomous",
    "limits": {
      "maxTokensPerRequest": 4096,
      "requestsPerMinute": 60,
      "toolCallsPerMinute": 30
    },
    "tools": [
      {
        "id": "builtin:http_fetch",
        "enabled": true
      }
    ],
    "a2aSkills": [
      {
        "id": "research_ingest",
        "name": "Ingest Source",
        "description": "Ingest a URL or raw content into long-term memory.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "research_ingest"
            },
            "url": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "content": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type"
          ],
          "anyOf": [
            {
              "required": [
                "url"
              ]
            },
            {
              "required": [
                "path"
              ]
            },
            {
              "required": [
                "content"
              ]
            }
          ]
        }
      },
      {
        "id": "research_query",
        "name": "Research Query",
        "description": "Answer a question using stored memory.",
        "inputSchema": {
          "type": "object",
          "properties": {
            "type": {
              "const": "research_query"
            },
            "question": {
              "type": "string"
            },
            "topK": {
              "type": "integer",
              "minimum": 1,
              "maximum": 20
            }
          },
          "required": [
            "type",
            "question"
          ]
        }
      }
    ]
  }
];
